/**
 * Renders every brand asset from the one geometry source
 * (../libs/brand/geometry.ts):
 *
 *   brand/mark.svg               — app icon / avatar
 *   brand/wordmark.svg           — lockup for light surfaces
 *   brand/wordmark-inverse.svg   — lockup for dark surfaces
 *   brand/og-card.svg            — 1200x630 social card (source of og-image.png)
 *   public/favicon.svg           — the icon the web demo serves
 *   public/favicon.png           — 48px PNG fallback
 *   public/apple-touch-icon.png  — 180px, full-bleed (iOS rounds it)
 *   public/og-image.png          — 1200x630, what og:image / twitter:image point at
 *   assets/icon.png              — 1024px native app icon (full-bleed square)
 *   assets/adaptive-icon.png     — 1024px Android adaptive foreground (no tile)
 *
 * These are committed, so this only needs re-running when the mark changes:
 *
 *   npm run brand
 *
 * The SVGs are plain strings; the PNGs are rasterised from those same strings
 * with resvg, so a PNG can never show a different mark than its SVG.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";

import {
  COLORS,
  FONT_STACK,
  STEM,
  STROKE_WIDTH,
  TAGLINE,
  TILE_RADIUS,
  VIEW_BOX,
  WORDMARK,
  WORDMARK_ADVANCE,
  WORDMARK_X,
  armPath,
} from "../libs/brand/geometry.ts";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");

/** The bare mark: tile, stem, and the two arms carrying the two tones. */
function mark({ toneOne, toneTwo, tile, radius = TILE_RADIUS }) {
  return [
    tile ? `<rect width="64" height="64" rx="${radius}" fill="${tile}"/>` : null,
    `<rect x="${STEM.x}" y="${STEM.y}" width="${STEM.width}" height="${STEM.height}" rx="${STEM.radius}" fill="${toneOne}"/>`,
    `<path d="${armPath(0)}" stroke="${toneOne}" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" fill="none"/>`,
    `<path d="${armPath(1)}" stroke="${toneTwo}" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" fill="none"/>`,
  ]
    .filter(Boolean)
    .join("\n  ");
}

const LABEL = `${WORDMARK.lead}${WORDMARK.trail}`;
/** Derived, not fixed — see WORDMARK_ADVANCE. The tspans sit on the same
 *  line as their <text>: under xml:space="preserve" any newline/indent
 *  inside it renders as leading spaces and shoves the wordmark right. */
const LOCKUP_WIDTH = Math.ceil(WORDMARK_X + LABEL.length * WORDMARK_ADVANCE + 16);

function markSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEW_BOX}" width="64" height="64" role="img" aria-label="${LABEL} mark">
  <title>${LABEL} mark</title>
  <!-- GENERATED by brand/build.mjs from libs/brand/geometry.ts. Do not hand-edit.
       The two arms carry the two tones, so the mark states the whole brand
       pair at 16px without needing the wordmark beside it. -->
  ${mark({ toneOne: COLORS.toneOne, toneTwo: COLORS.toneTwo, tile: COLORS.tile })}
</svg>
`;
}

/**
 * Native app icon: full-bleed square. iOS and most launchers apply their own
 * corner mask, and a pre-rounded tile would show its transparent corners.
 */
function appIconSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEW_BOX}" width="64" height="64">
  ${mark({ toneOne: COLORS.toneOneInverse, toneTwo: COLORS.toneTwo, tile: COLORS.tile, radius: 0 })}
</svg>
`;
}

/**
 * Android adaptive-icon foreground: the tile comes from
 * `android.adaptiveIcon.backgroundColor`, and the launcher masks the layer to
 * its own shape, so the mark is drawn alone and shrunk into the 66% safe zone.
 */
function adaptiveForegroundSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEW_BOX}" width="64" height="64">
  <g transform="translate(32 32) scale(0.6) translate(-32 -32)">
  ${mark({ toneOne: COLORS.toneOneInverse, toneTwo: COLORS.toneTwo, tile: null })}
  </g>
</svg>
`;
}

/**
 * Lockup = mark + wordmark. The gap is half the mark's height, which is also
 * the clear space the mark keeps on every side.
 */
function wordmarkSvg({ inverse }) {
  const toneOne = inverse ? COLORS.toneOneInverse : COLORS.toneOne;
  const tile = inverse ? COLORS.tileInverse : COLORS.tile;
  const text = inverse ? COLORS.foregroundInverse : COLORS.foreground;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${LOCKUP_WIDTH} 64" width="${LOCKUP_WIDTH}" height="64" role="img" aria-label="${LABEL}">
  <title>${LABEL}</title>
  <!-- GENERATED by brand/build.mjs. The text is set live in Geist SemiBold
       with a system fallback; outline it before export for print or any
       surface that cannot load Geist. -->
  ${mark({ toneOne, toneTwo: COLORS.toneTwo, tile })}
  <text x="${WORDMARK_X}" y="41" font-family="${FONT_STACK}"
        font-size="26" font-weight="600" letter-spacing="-0.5" xml:space="preserve"><tspan fill="${toneOne}">${WORDMARK.lead}</tspan><tspan fill="${text}">${WORDMARK.trail}</tspan></text>
</svg>
`;
}

function ogCardSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630" role="img" aria-label="${LABEL} — ${TAGLINE}">
  <title>${LABEL} — ${TAGLINE}</title>
  <!-- GENERATED by brand/build.mjs. -->
  <defs>
    <radialGradient id="glow" cx="18%" cy="12%" r="85%">
      <stop offset="0%" stop-color="${COLORS.toneOne}" stop-opacity="0.30"/>
      <stop offset="60%" stop-color="${COLORS.toneOne}" stop-opacity="0.04"/>
      <stop offset="100%" stop-color="${COLORS.toneOne}" stop-opacity="0"/>
    </radialGradient>
    <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
      <path d="M40 0 L0 0 0 40" fill="none" stroke="${COLORS.grid}" stroke-width="1"/>
    </pattern>
  </defs>
  <rect width="1200" height="630" fill="${COLORS.tileInverse}"/>
  <rect width="1200" height="630" fill="url(#grid)"/>
  <rect width="1200" height="630" fill="url(#glow)"/>

  <g transform="translate(96 168) scale(1.5)">
    ${mark({ toneOne: COLORS.toneOneInverse, toneTwo: COLORS.toneTwo, tile: COLORS.tile })}
  </g>

  <text x="96" y="352" font-family="${FONT_STACK}"
        font-size="76" font-weight="600" letter-spacing="-2" xml:space="preserve"><tspan fill="${COLORS.toneOneInverse}">${WORDMARK.lead}</tspan><tspan fill="${COLORS.foregroundInverse}">${WORDMARK.trail}</tspan></text>
  <text x="96" y="410" font-family="${FONT_STACK}"
        font-size="28" font-weight="400" fill="${COLORS.foregroundMutedInverse}">${TAGLINE}</text>
</svg>
`;
}

function png(svg, width) {
  return new Resvg(svg, {
    fitTo: { mode: "width", value: width },
    font: { loadSystemFonts: true, defaultFontFamily: "Segoe UI" },
  })
    .render()
    .asPng();
}

const written = [];
function write(relative, contents) {
  const target = path.join(ROOT, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents);
  written.push(relative);
}

const MARK = markSvg();
const OG = ogCardSvg();

write("brand/mark.svg", MARK);
write("brand/wordmark.svg", wordmarkSvg({ inverse: false }));
write("brand/wordmark-inverse.svg", wordmarkSvg({ inverse: true }));
write("brand/og-card.svg", OG);
write("public/favicon.svg", MARK);
write("public/favicon.png", png(MARK, 48));
write("public/apple-touch-icon.png", png(appIconSvg(), 180));
write("public/og-image.png", png(OG, 1200));
write("assets/icon.png", png(appIconSvg(), 1024));
write("assets/adaptive-icon.png", png(adaptiveForegroundSvg(), 1024));

console.log(`Brand assets written — ${written.join(", ")}`);
